[[enable-phone-home]]
= enable-phone-home

Enables the phone home services.

[[synopsis]]
== Synopsis

[source, shell]
----
asadmin> enable-phone-home
----

[[description]]
== Description

The phone home data is presently used to gather usage statistics about the corresponding distribution, such as how long users typically run instances, and what versions they use.
The phone home service is enabled by default when starting a Payara Server.


[[examples]]
== Examples

*Example 1 Enable Phone Home Service*

[source, shell]
----
asadmin>  enable-phone-home
Phone Home Service is enabled

Command enable-phone-home executed successfully.
----

[[exit-status]]
== Exit Status

0::
command executed successfully
1::
error in executing the command

*See Also*

* xref:technical-documentation/payara-server-documentation/command-reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:technical-documentation/payara-server-documentation/command-reference/disable-phone-home.adoc#disable-phone-home[`disable-phone-home`],
* xref:technical-documentation/payara-server-documentation/command-reference/list-phone-home.adoc#list-phone-home[`list-phone-home`]

