= Get-Rest-Monitoring-Configuration

Retrieves the REST monitoring service general settings.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-rest-monitoring-configuration
[--help]
[--target target]
----

[[description]]
== Description

This command can be used to view the current configuration of the JMX monitoring service.

[[options]]
== Options

*asadmin-options*:
Options for the `asadmin` utility. For information about these options, see the xref:technical-documentation/payara-server-documentation/command-reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
*`--help`*:
*`-?`*:
Displays the help text for the subcommand.
*`--target`*:
This option helps specify the target on which you are retrieving the REST monitoring service configuration. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
cluster_name;;
Applies to every server instance in the cluster.
instance_name;;
Applies to a specified server instance.

[[examples]]
== Examples

*Example 1 Get current REST monitoring service configuration*

[source, shell]
----
asadmin get-rest-monitoring-configuration
Rest Monitoring Enabled  Rest Monitoring Application Name  Context Root      Security Enabled
false                    __restmonitoring                  /rest-monitoring  false
----

[[exit-status]]
== Exit Status

*0*:
subcommand executed successfully
*1*:
error in executing the subcommand

*See Also*

* xref:technical-documentation/payara-server-documentation/command-reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:technical-documentation/payara-server-documentation/command-reference/monitoring.adoc[Monitoring Basics],
* xref:technical-documentation/payara-server-documentation/command-reference/set-rest-monitoring-configuration.adoc[`set-rest-monitoring-configuration`]
