= Configuring the Access Log
:ordinal: 2

Payara Micro supports a number of commands to help you configure access logging. It is easiest to configure access logging before it is bootstrapped, however you can edit `domain.xml` also, as Payara Micro can reload that dynamically.

[cols="2,3,2",options="header",]
|============================
| Configuration Option | Description | Default Value

a|[.breakable]`--accesslog <directory-path>`
|Sets user defined directory path for the access log
|

a|[.breakable]`--accesslogformat`
|Sets user defined log format for the access log
a|`%client.name% %auth-user-name% %datetime% %request% %status% %response.length%`

a|[.breakable]`--accessloginterval`
|Sets user defined access log write interval
|300

a|[.breakable]`--accesslogsuffix`
|Sets user defined simple date time suffix for access log filenames
a|`yyyy-MM-dd`

a|[.breakable]`--accesslogprefix`
|Sets user defined prefix for access log filenames
|

|============================

All options available for configuring Payara Micro can be seen by running the JAR with the `--help` option, or by consulting xref:../../payara-micro-configuration-and-management/micro-management/command-line-options/command-line-options.adoc[Payara Micro Command Line Options]

[#usage-examples]
== Usage Examples

[cols="2,3,2",options="header",]
|============================
|Configuration Option| Usage| Result

a|[.breakable]`--accesslog`
a|[.breakable]`java -jar payara-micro --accesslog ~/logs/accesslogs`
| Access logging is enabled

a|`--accesslogformat`
a|[.breakable]`java -jar payara-micro --accesslog ~/logs/accesslogs --accesslogformat %u %t %s %b`
| Payara [22/11/2019:09:24:36 00] 200 532

a|`--accessloginterval`
a|[.breakable]`java -jar payara-micro --accesslog ~/logs/accesslogs --accessloginterval 0`
| Access log write interval is set to write its buffer to file immediately

a|`--accesslogsuffix`
a|[.breakable]`java -jar payara-micro --accesslog ~/logs/accesslogs --accesslogsuffix %hh%mm%a`
| server_access_log.%09%30%AM.txt

a|`--accesslogprefix`
a|[.breakable]`java -jar payara-micro --accesslog ~/logs/accesslogs --accesslogprefix Production`
| Production.2019-11-22.txt

|============================
