= The `asadmin` Deployment Subcommands
:ordinal: 2

This appendix lists the `asadmin` deployment subcommands that are included with this release of the Payara Server software.
For information on additional `asadmin` subcommands, see "xref:../general-administration/subcommands-for-the-asadmin-cli.adoc#subcommands-for-the-asadmin-utility[Subcommands for the `asadmin` Utility]" in the __Payara Server General Administration section__.

xref:technical-documentation/payara-server-documentation/command-reference/add-library.adoc[`add-library`] +
Adds one or more library JAR files to Payara Server. You can specify whether the libraries are added to the Common class loader directory, the Jakarta optional package directory, or the application-specific class loader directory.

xref:technical-documentation/payara-server-documentation/command-reference/create-application-ref.adoc[`create-application-ref`] +
Creates a reference from a cluster or an un-clustered server instance to a previously deployed Jakarta EE application or module. This effectively results in the application element being deployed and made available on the targeted instance or cluster.

xref:technical-documentation/payara-server-documentation/command-reference/delete-application-ref.adoc[`delete-application-ref`] +
Removes a reference from a cluster or an un-clustered server instance to a previously deployed Jakarta EE application or module. This effectively results in the application element being un-deployed on the targeted instance or cluster.

xref:technical-documentation/payara-server-documentation/command-reference/deploy.adoc[`deploy`] +
Deploys an enterprise application, web application, EJB module, connector module, or application client module. If the component is already deployed or already exists, you can forcefully redeploy if you set the `--force` option to `true`. +
A directory can also be deployed. Supported in remote mode only. For usage instructions, see xref:deploying-applications.adoc#to-deploy-an-application-or-module[To Deploy an Application or Module].

xref:../command-reference/deploy-remote-archive.adoc[`deploy-remote-archive`] +
Deploys an enterprise application, web application, EJB module, connector module, or application client module from a remote location, either using a URL or a set of Maven GAV coordinates. +
For usage instructions, see xref:deploying-applications.adoc#to-deploy-from-a-url[To Deploy from a URL] and xref:deploying-applications.adoc#to-deploy-using-maven-artifact[To Deploy using a Maven Artifact].

xref:technical-documentation/payara-server-documentation/command-reference/disable.adoc[`disable`] +
Immediately deactivates the named application or module. If the component has not been deployed, an error message is returned. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-disable-an-application-or-module[To Disable an Application or Module].

xref:technical-documentation/payara-server-documentation/command-reference/enable.adoc[`enable`] +
Enables the specified application or module. If the component has not been deployed, an error message is returned. If the component is already enabled, then it is re-enabled. +
Supported in remote mode only. For usage instructions, see xref:deploying-applications.adoc#to-enable-an-application-or-module[To Enable an Application or Module].

xref:technical-documentation/payara-server-documentation/command-reference/get-client-stubs.adoc[`get-client-stubs`] +
Gets the client stubs JAR file for an application client module or an application containing the application client module, from the server machine to the local directory. +
For usage instructions, see xref:deploying-applications.adoc#ejb-module-deployment-guidelines[EJB Module Deployment Guidelines].

xref:technical-documentation/payara-server-documentation/command-reference/list-applications.adoc[`list-applications`] +
Lists deployed Jakarta EE applications and modules. Optionally lists subcomponents and scoped resources. If the `--type` option is not specified, all applications and modules are listed. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-list-deployed-applications-or-modules[To List Deployed Applications or Modules].

xref:technical-documentation/payara-server-documentation/command-reference/list-application-refs.adoc[`list-application-refs`] +
Lists Jakarta EE applications and modules deployed on the specified target server instance or cluster.

xref:technical-documentation/payara-server-documentation/command-reference/list-libraries.adoc[`list-libraries`] +
Lists library JAR files that have been added to Payara Server. You can specify whether to list libraries in the Common class loader directory, the Jakarta optional package directory, or the application-specific class loader directory.

xref:technical-documentation/payara-server-documentation/command-reference/list-sub-components.adoc[`list-sub-components`] +
Lists EJBs or servlets in a deployed module or in a module of the deployed application. +
If a module is not identified, all modules are listed. To display a specific module in an application, you must specify the module name and the `--appname` option. +
Supported in remote mode only. For usage instructions, see xref:deploying-applications.adoc#to-list-deployed-applications-or-modules[To List Deployed Applications or Modules].

xref:technical-documentation/payara-server-documentation/command-reference/list-web-context-param.adoc[`list-web-context-param`] +
Lists servlet context-initialization parameters of a deployed web application or module. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-list-web-context-parameters[To List Web Context Parameters].

xref:technical-documentation/payara-server-documentation/command-reference/list-web-env-entry.adoc[`list-web-env-entry`] +
Lists environment entries for a deployed web application or module. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-list-web-environment-entries[To List Web Environment Entries].

xref:technical-documentation/payara-server-documentation/command-reference/redeploy.adoc[`redeploy`] +
Overwrites an application or module that is already deployed. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-redeploy-an-application-or-module[To Redeploy an Application or Module].

xref:technical-documentation/payara-server-documentation/command-reference/remove-library.adoc[`remove-library`] +
Removes one or more library JAR files from Payara Server. You can specify whether the libraries are removed from the Common class loader directory, the Jakarta optional package directory, or the application-specific class loader directory.

xref:technical-documentation/payara-server-documentation/command-reference/set-web-context-param.adoc[`set-web-context-param`] +
Sets a servlet context-initialization parameter of a deployed web application or module. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-set-a-web-context-parameter[To Set a Web Context Parameter].

xref:technical-documentation/payara-server-documentation/command-reference/set-web-env-entry.adoc[`set-web-env-entry`] +
Sets an environment entry for a deployed web application or module. +
Supported in remote mode only. For usage instructions, see
  xref:deploying-applications.adoc[To Set a Web Environment Entry].

xref:technical-documentation/payara-server-documentation/command-reference/show-component-status.adoc[`show-component-status`] +
Shows the status of a deployed component. The possible statuses include `enabled` or `disabled`. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-set-a-web-environment-entry[To List Deployed Applications or Modules].

xref:technical-documentation/payara-server-documentation/command-reference/undeploy.adoc[`undeploy`] +
Uninstalls the specified deployed application or module. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-undeploy-an-application-or-module[To Undeploy an Application or Module].

xref:technical-documentation/payara-server-documentation/command-reference/unset-web-context-param.adoc[`unset-web-context-param`] +
Unsets a servlet context-initialization parameter of a deployed web application or module. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-unset-a-web-context-parameter[To Unset a Web Context Parameter].

xref:technical-documentation/payara-server-documentation/command-reference/unset-web-env-entry.adoc[`unset-web-env-entry`] +
Unsets an environment entry for a deployed web application or module. Supported in remote mode only. +
For usage instructions, see xref:deploying-applications.adoc#to-unset-a-web-environment-entry[To Unset a Web Environment Entry].
