= Asadmin-Recorder-Enabled

Returns whether the Asadmin Recorder service is enabled .

[#synopsis]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] asadmin-recorder-enabled [--help]
----

[#description]
== Description

The `asadmin-recorder-enabled` command checks if the Asadmin Recorder feature is active in Payara Server, simply returning a true or false status.

[#options]
== Options

*asadmin-options*:
Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
*`--help`*:
*`-?`*:
Displays the help text for the subcommand.

[#examples]
== Examples

*Example 1*

Returns whether the Asadmin Recorder Service is enabled or not.

[source, shell]
----
asadmin> asadmin-recorder-enabled
Asadmin Recorder Service is enabled
Command asadmin-recorder-enabled executed successfully.
----

[#exit-status]
== Exit Status

*0*:
subcommand executed successfully
*1*:
error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:set-asadmin-recorder-configuration.adoc#set-asadmin-recorder-configuration[`set-asadmin-recorder-configuration`],
* xref:get-asadmin-recorder-configuration.adoc#get-asadmin-recorder-configuration[`get-asadmin-recorder-configuration`],
* xref:enable-asadmin-recorder.adoc#enable-asadmin-recorder[`enable-asadmin-recorder`],
* xref:disable-asadmin-recorder.adoc#disable-asadmin-recorder[`disable-asadmin-recorder`]



