= Clear-Cache

Clears a Hazelcast or JCache IMap.

[#synopsis]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] clear-cache
[--help]
[--target target]
[--cachename cachename]
----

[#description]
== Description

This command can be used to clear a Hazelcast or JCache IMap.

WARNING: Use of this command removes all data from a cache and therefore can result in unexpected behaviour if a system cache is cleared. +
Clearing a cache containing web session data will result in all users losing their sessions, for example.

[#options]
== Options

*asadmin-options*:
Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
*`--help`*:
*`-?`*:
Displays the help text for the subcommand.
*`--target`*:
This option helps specify the target on which you are executing this operation. Valid values are: +
`server`;;
Applies to the default server instance. This is the default value.
instance_name;;
Applies to a specified server instance.
*`--cachename`*:
Name of the cache/map to clear.

[#examples]
== Examples

*Example 1 Clears a Hazelcast or JCache IMap*

[source, shell]
----
asadmin> clear-cache --cachename payara.instance.store
Cleared Cache payara.instance.store
Command clear-cache executed successfully.
----

[#exit-status]
== Exit Status

*0*:
subcommand executed successfully
*1*:
error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`],
* xref:../high-availability/administering-the-domain-data-grid.adoc[Domain Data Grid],
* xref:list-hazelcast-cluster-members.adoc[`list-hazelcast-cluster-members`],
* xref:list-hazelcast-members.adoc[`list-hazelcast-members`],
* xref:restart-hazelcast.adoc[`restart-hazelcast`],
* xref:list-cache-keys.adoc[`list-cache-keys`],
* xref:list-caches.adoc[`list-caches`],
* xref:set-hazelcast-configuration.adoc[`set-hazelcast-configuration`],
* xref:get-hazelcast-configuration.adoc[`get-hazelcast-configuration`],
* xref:generate-encryption-key.adoc[`generate-encryption-key`]
