= Generate-Encryption-Key

Generates an encryption key for Data Grid secure communication.

[#synopsis]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] generate-encryption-key
[--help]
[--dontCheckIfRunning={true|false}]
[--domaindir domaindir]
[domain-name]
----

[#description]
== Description

This command can be used to generate an encryption key used by Payara Server to perform encryption and decryption of the data stored within the Data Grid.

For more information on the Data Grid mechanism, see xref:../high-availability/administering-the-domain-data-grid.adoc#datagrid-encryption[Data Grid Encryption].

[#options]
== Options

*asadmin-options*:
Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
*`--help`*:
*`-?`*:
Displays the help text for the subcommand.
*`--dontCheckIfRunning`*:
Determines whether to check if the targeted domain is running or not.
+
The default value is `false`.
*`--domaindir`*:
The path to the directory containing the target domain. The default domain directory is `as-install/domains`.

[#operands]
== Operands

*domain-name*:
The name of the domain to target. The default is `domain1`.

[#examples]
== Examples

*Example 1 Generates an encryption key.*

This example generates an encryption key used by Payara Server to perform encryption and decryption of the data stored within the data grid.

[source, shell]
----
asadmin> generate-encryption-key
Enter the current master password>
Command generate-encryption-key executed successfully.
----

[#exit-status]
== Exit Status

*0*:
subcommand executed successfully
*1*:
error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`],
* xref:../high-availability/administering-the-domain-data-grid.adoc[Domain Data Grid],
* xref:list-hazelcast-cluster-members.adoc[`list-hazelcast-cluster-members`],
* xref:list-hazelcast-members.adoc[`list-hazelcast-members`],
* xref:restart-hazelcast.adoc[`restart-hazelcast`],
* xref:list-cache-keys.adoc[`list-cache-keys`],
* xref:list-caches.adoc[`list-caches`],
* xref:clear-cache.adoc[`clear-cache`],
* xref:set-hazelcast-configuration.adoc[`set-hazelcast-configuration`],
* xref:get-hazelcast-configuration.adoc[`get-hazelcast-configuration`]
