= Get-Asadmin-Recorder-Configuration

Returns the current configuration of the Asadmin Recorder service.

[#synopsis]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] get-asadmin-recorder-configuration [--help]
----

[#description]
== Description

The `get-asadmin-recorder-configuration` command is used to retrieve the current configuration settings of the Asadmin Recorder feature in Payara Server.

[#options]
== Options

*asadmin-options*:
Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.
*`--help`*:
*`-?`*:
Displays the help text for the subcommand.

[#examples]
== Examples

*Example 1*

Returns the current configuration of the asadmin recorder.

[source, shell]
----
asadmin> get-asadmin-recorder-configuration
Enabled  Filter Commands  Output Location                  Filtered Commands                                                               Prepend Enabled  Prepended Options
true     true             /home/user/asadmin-commands.txt  version,_(.*),list(.*),get(.*),(.*)-list-services,uptime,enable-asadmin-recorder,disable-asadmin-recorder,set-asadmin-recorder-configuration,asadmin-recorder-enabledfalse
Command get-asadmin-recorder-configuration executed successfully.
----

[#exit-status]
== Exit Status

*0*:
subcommand executed successfully
*1*:
error in executing the subcommand

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:set-asadmin-recorder-configuration.adoc#set-asadmin-recorder-configuration[`set-asadmin-recorder-configuration`],
* xref:enable-asadmin-recorder.adoc#enable-asadmin-recorder[`enable-asadmin-recorder`],
* xref:disable-asadmin-recorder.adoc#disable-asadmin-recorder[`disable-asadmin-recorder`],
* xref:asadmin-recorder-enabled.adoc#asadmin-recorder-enabled[`asadmin-recorder-enabled`],



