= List-Admin-Objects

Gets all the administered objects.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] list-admin-objects [--help] 
[target]
----

[[description]]
== Description

The `list-admin-objects` subcommand lists all the administered objects.

This subcommand is supported in remote mode only.

[[options]]
== Options

*asadmin-options*:
  Options for the `asadmin` utility. For information about these
  options, see the xref:technical-documentation/payara-server-documentation/command-reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
*`--help`*:
*`-?`*:
  Displays the help text for the subcommand.

[[operands]]
== Operands

*target*:
  The target for which administered objects are to be listed. Valid values are as follows: +
  `server`;;
    Lists the administered objects on the default server instance. This is the default value.
  configuration-name;;
    Lists the administered objects in the specified configuration.
  cluster-name;;
    Lists the administered objects on all server instances in the specified cluster.
  instance-name;;
    Lists the administered objects on a specified server instance.

[[examples]]
== Examples

*Example 1 Listing Administered Objects*

This example lists all the administered objects.

[source,shell]
----
asadmin> list-admin-objects
jms/samplequeue
jms/anotherqueue
Command list-admin-objects executed successfully
----

[[exit-status]]
== Exit Status

*0*:
  subcommand executed successfully
*1*:
  error in executing the subcommand

*See Also*

* xref:technical-documentation/payara-server-documentation/command-reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:technical-documentation/payara-server-documentation/command-reference/create-admin-object.adoc#create-admin-object[`create-admin-object`],
* xref:technical-documentation/payara-server-documentation/command-reference/delete-admin-object.adoc#delete-admin-object[`delete-admin-object`]
