= Restart-Http-Listeners

 Restarts all HTTP network listener of the targeted instance(s).

[#synopsis]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] restart-http-listeners
[--help]
[--all={true|false}]
[target]
----

[#description]
== Description

The `restart-http-listeners` subcommand restarts an HTTP network listener of the targeted instance(s).

IMPORTANT: This command only restarts all HTTP listeners except `admin-listener`.

[#options]
== Options

*asadmin-options*:
  Options for the `asadmin` utility. For information about these options, see the xref:asadmin.adoc#asadmin-1m[`asadmin`] help page.

*`--help`*:
*`-?`*:
  Displays the help text for the subcommand.

*`--all`*:
Applies the command to all instances. The default value is `false`.

[#operands]
== Operands

*target*:
Name of the target instance, deployment group or cluster to which restart the corresponding HTTP listeners.

[#examples]
== Examples

*Example 1 Restarting an HTTP Network Listener*

The following command to restart all HTTP network listeners that belong to a particular instance named `i1`:

[source,shell]
----
asadmin>restart-http-listeners i1
Command restart-http-listeners executed successfully.
----

[#exit-status]
== Exit Status

*0*:
  command executed successfully
*1*:
  error in executing the command

*See Also*

* xref:asadmin.adoc#asadmin-1m[`asadmin`]
* xref:create-ssl.adoc#create-ssl[`create-ssl`],
* xref:create-network-listener.adoc#create-network-listener[`create-network-listener`],
* xref:set-network-listener-configuration.adoc#set-network-listener-configuration[`set-network-listener-configuration`],
* xref:create-virtual-server.adoc#create-virtual-server[`create-virtual-server`],
* xref:create-http-listener.adoc#create-http-listener[`create-http-listener`],
* xref:delete-http-listener.adoc#delete-http-listener[`delete-http-listener`],
* xref:list-http-listeners.adoc#list-http-listeners[`list-http-listeners`],
* xref:restart-http-listeners.adoc#restart-http-listeners[`restart-http-listeners`]
