= Stop-All-Domains

Stops the Domain Administration Server(DAS) of all current running domains on the server’s installation.

[#synopsis]
== Synopsis

[source,shell]
----
asadmin stop-all-domains [--help]
[--force={true|false}]
[--kill={true|false}]
[--timeout timeout]
[--domainTimeout timeout]
----

[#description]
== Description

The `stop-all-domains` subcommand can be used to stop ALL current running domains on the server’s installation.

[#options]
== Options

*`--force`*:
Specifies whether each domain is forcibly stopped immediately.
+
The default value is `true`.

*`--kill`*:
Specifies whether the domain is killed by using functionality of the operating system to terminate the domain process.
+
The default value is `false`.

*`--timeout`*:
Specifies how long to take for the domains to stop in seconds. If stopping the domains takes longer than this amount then this command will fail.
+
The default value is `600`.

*`--domainTimeout`*:
Specifies how long to take for each domain to stop in seconds. If stopping the domain takes longer than this amount then this command will fail
+
The default value is `600`.

[#examples]
== Examples

*Example 1 Stopping Domains*

This example stops all currently running domains on the server’s installation.

[source,shell]
----
asadmin stop-all-domains

Stopping domain domain1
Stopped domain
Stopping domain production
Stopped domain
Stopping domain test
Stopped domain
Stopping domain testy
Stopped domain
Command stop-all-domains executed successfully.
----

[#exit-status]
== Exit Status

*0*:
  subcommand executed successfully
*1*:
  error in executing the subcommand

*See Also*

* xref:technical-documentation/payara-server-documentation/command-reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:technical-documentation/payara-server-documentation/command-reference/create-domain.adoc#create-domain[`create-domain`],
* xref:technical-documentation/payara-server-documentation/command-reference/delete-domain.adoc#delete-domain[`delete-domain`],
* xref:technical-documentation/payara-server-documentation/command-reference/list-domains.adoc#list-domains[`list-domains`],
* xref:technical-documentation/payara-server-documentation/command-reference/restart-domain.adoc#restart-domain[`restart-domain`],
* xref:technical-documentation/payara-server-documentation/command-reference/restart-domains.adoc#restart-domains[`restart-domains`],
* xref:technical-documentation/payara-server-documentation/command-reference/start-domain.adoc#start-domain[`start-domain`],
* xref:technical-documentation/payara-server-documentation/command-reference/start-domains.adoc#start-domains[`start-domains`],
* xref:technical-documentation/payara-server-documentation/command-reference/stop-domain.adoc#stop-domain[`stop-domain`],
* xref:technical-documentation/payara-server-documentation/command-reference/stop-domains.adoc#stop-domains[`stop-domains`]
