= Unfreeze-Transaction-Service

Resumes all suspended transactions.

[[synopsis]]
== Synopsis

[source,shell]
----
asadmin [asadmin-options] unfreeze-transaction-service [--help]
[--target target]
----

[[description]]
== Description

The `unfreeze-transaction-service` subcommand restarts the transaction subsystem and resumes all in-flight transactions. Invoke this subcommand
on an already frozen transaction subsystem.

This subcommand is supported in remote mode only.

[[options]]
== Options

*asadmin-options*:
  Options for the `asadmin` utility. For information about these options, see the xref:technical-documentation/payara-server-documentation/command-reference/asadmin.adoc#asadmin-1m[`asadmin`] help page.
*`--help`*:
*`-?`*:
  Displays the help text for the subcommand.
*`--target`*:
  This option specifies the target on which you are unfreezing the transaction service. Valid values are: +
  `server`;;
    Unfreezes the transaction service for the default server instance `server` and is the default value.
  configuration_name;;
    Unfreezes the transaction service for all server instances that use the named configuration.
  cluster_name;;
    Unfreezes the transaction service for every server instance in the cluster.
  instance_name;;
    Unfreezes the transaction service for a particular server instance.

[[examples]]
== Examples

*Example 1 Using unfreeze-transaction-service*

[source,shell]
----
% asadmin unfreeze-transaction-service
Command unfreeze-transaction-service executed successfully
----

[[exit-status]]
== Exit Status

*0*:
  command executed successfully
*1*:
  error in executing the command

*See Also*

* xref:technical-documentation/payara-server-documentation/command-reference/asadmin.adoc#asadmin-1m[`asadmin`],
* xref:technical-documentation/payara-server-documentation/command-reference/freeze-transaction-service.adoc#freeze-transaction-service[`freeze-transaction-service`],
* xref:technical-documentation/payara-server-documentation/command-reference/recover-transactions.adoc#recover-transactions[`recover-transactions`],
* xref:technical-documentation/payara-server-documentation/command-reference/rollback-transaction.adoc#rollback-transaction[`rollback-transaction`]
* xref:technical-documentation/payara-server-documentation/general-administration/administering-transactions.adoc#administering-transactions[Administering Transactions] in Payara Server General Administration section
* https://jakarta.ee/specifications/transactions/2.0/[Transactions^]


