:ordinal: 4
= Payara Micro Managed Arquillian Container Adapter

When using this adapter, the Payara Micro container lifecycle is managed by Arquillian by starting a separate JVM process to launch and stop a Payara Micro instance locally.

[#usage]
== Usage

The Payara Micro Managed Arquillian container adapter can be found on https://central.sonatype.com/artifact/fish.payara.arquillian/arquillian-payara-micro-managed[Maven Central^], and can be included in your project using the following Maven GAV coordinates:

[source,XML]
----
<dependency>
  <groupId>fish.payara.arquillian</groupId>
  <artifactId>arquillian-payara-micro-managed</artifactId>
  <version>${release-id}</version>
</dependency>
----

[#configuration]
== Container Configuration

The Payara Micro container can be configured via the `arquillian.xml` file using the standard http://arquillian.org/arquillian-core/#container-configuration[Arquillian Container Configuration^] mechanism.

The following configuration options are available:

[cols="2,3,2,2,1"]
.Configuration Options
|===
| Container Option | Description | System Property | Environment Variable | Default

a| `microJar`
| Provides the location of the Payara Micro Jar.
a| `payara.microJar`
a| `MICRO_JAR`
|

a| `startupTimeoutInSeconds`
| Specifies the amount of time in seconds that the container will wait for Payara Micro to start.
a| `payara.startupTimeoutInSeconds`
a| `MICRO_STARTUP_TIMEOUT_IN_SECONDS`
a| `180`

a| `randomHttpPort`
| Randomises the initial HTTP port of Payara Micro. This saves time by avoiding collisions with the default port.
a| `payara.randomHttpPort`
a| `MICRO_RANDOM_HTTP_PORT`
a| `true`

a| `autoBindHttp`
a| Enables the `--autoBindHttp` option for the Micro instance.
a| `payara.autoBindHttp`
a| `MICRO_AUTOBIND_HTTP`
a| `true`

a| `clusterEnabled`
| Enables clustering on the Micro instance.
a| `payara.clusterEnabled`
a| `MICRO_CLUSTER_ENABLED`
a| `false`

a| `consoleOutput`
| Enables/disables console output on the Micro instance.
a| `payara.consoleOutput`
a| `MICRO_CONSOLE_OUTPUT`
a| `true`

a| `debug`
a| Enables debugging on the Payara Micro instance.

By default, Payara Micro will wait for the debugger on port `5005` before starting.

Disables the startup timeout.

To change this, provide java debug options to `cmdOptions`.
a| `payara.debug`
a| `MICRO_DEBUG`
a| `false`

a| `cmdOptions`
| Provides JVM options to the Java process running the Micro instance.
a| `payara.cmdOptions`
a| `MICRO_CMD_OPTIONS`
|

a| `extraMicroOptions`
| Provides standard Payara Micro arguments for the server instance to launch with
a| `payara.extraMicroOptions`
a| `EXTRA_MICRO_OPTIONS`
|

|===

[#examples]
== Examples

To configure the options using Arquillian container properties, you need to use an `arquillian.xml` file placed on the test classpath.

Here's an example `arquillian.xml` file. It configures `randomHttpPort` and `autoBindHttp` options.

[source,XML]
.Example `arquillian.xml` file
[source,text]
----
<?xml version="1.0"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://jboss.org/schema/arquillian"
            xsi:schemaLocation="http://jboss.org/schema/arquillian
                http://jboss.org/schema/arquillian/arquillian_1_0.xsd">
    <container qualifier="payara-micro-managed" default="true">
        <configuration>
            <property name="randomHttpPort">false</property>
            <property name="autoBindHttp">false</property>
        </configuration>
    </container>
</arquillian>
----

You can configure the options also using system properties. Here's an example configuration if you run your tests using the maven `surefire` plugin:

[source, xml]
.Example - Surefire plugin configuration in the project's POM file
[source,text]
----
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-surefire-plugin</artifactId>
    <configuration>
        <systemPropertyVariables>
            <arquillian.launch>payara-micro-managed</arquillian.launch>
            <payara.randomHttpPort>false</payara.randomHttpPort>
            <payara.autoBindHttp>false</payara.autoBindHttp>
        </systemPropertyVariables>
    </configuration>
</plugin>
----

You can also configure the options using environment variables, for example when running the maven `mvn test` command:

[source,shell]
----
export MICRO_RANDOM_HTTP_PORT=false
export MICRO_AUTOBIND_HTTP=false

mvn test
----
