= Payara Micro Apache Netbeans IDE Support
:page-description: Payara Micro tools in Apache NetBeans IDE — create and run Payara Micro projects with MicroProfile support and hot deploy from Apache NetBeans.
:ordinal: 2

Apache NetBeans has Payara Micro support built into the IDE, so there is no need to install a plugin to integrate and control Payara Micro from Apache NetBeans.

[#create-micro-project]
== Creating a Payara Micro Project

Apache NetBeans IDE supports Payara Micro out of the box. To create a Payara Micro project, follow these steps:

. Create a new project using Payara Micro Application archetype under Java with Maven category.
+
*image*: apache-netbeans/payara-micro/netbeans-new-project-payara6.png[New Payara Micro Maven Project]
+
. Input the desired project name, project name, artifact id, group id and version.
+
*image*: apache-netbeans/payara-micro/netbeans-new-application-payara6.png[]
+
. Select the desired Payara Micro version. Make sure that Auto Bind HTTP is left unchecked.
+
*image*: apache-netbeans/payara-micro/netbeans-new-application-version-payara6.png[]

[#deploy-payara-micro-project]
== Deploying the Payara Micro Project

To deploy the Payara Micro project, simply run the application using the Run Project option from the Run menu. The Payara Micro application will be deployed and the URL will be displayed in the _Output_ window:

*image*: apache-netbeans/payara-micro/netbeans-app-running-payara6.png[]

[#hot-deploy-and-auto-deploy-settings]
== Hot Deploy and Auto Deploy Settings

To enable the *Auto Deploy* features for Payara Micro on the Apache NetBeans IDE, you must enable the *Compile on Save* and *Deploy on Save* features from the *Project Properties*.

*Compile on Save* can be found in the *Build->Compile* submenu of the project properties.

*image*: hot-auto-deploy/netbeans-autodeploy-1-micro.png[Auto Deploy 1]

*Deploy on Save* can be found in the Run submenu of the project properties.

*image*: hot-auto-deploy/netbeans-autodeploy-2-micro.png[Auto Deploy 2]

To enable the *Hot Deploy* feature for Payara Micro on the Apache NetBeans IDE, you must enable the *Hot Deploy* checkbox which can be found in the *Payara Micro* submenu of the project properties.

*image*: hot-auto-deploy/netbeans-hotdeploy-micro.png[Hot Deploy Micro]

[#see-also]
== See Also
xref:../hot-deploy-and-auto-deploy.adoc[Hot Deploy and Auto Deploy]
